apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: text2image-front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YahiaDev/text2imageFrontKubernetesConfig.git
    targetRevision: HEAD
    path: overlays/dev/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: text2image

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true # if a cluster is modified manualy agrocd wil undo the change
      prune: true # if a component is deleted/ or rename in yaml file argocd will deleted it


