apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: text2image-front-deployment
  name: text2image-front-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: text2image-front-deployment
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: text2image-front-deployment
  name: text2image-front-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text2image-front-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: text2image-front-deployment
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        image: yahiadev/text2imagefront:0.0.1
        imagePullPolicy: Always
        name: text2image-front-deployment
        ports:
        - containerPort: 8081
        resources: {}
status: {}
