apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: text2image-front-deployment
  name: text2image-front-service
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: text2image-front-deployment
  type: NodePort
status:
  loadBalancer: {}
